### ISSUE TITLE
Prüfung des Betreffs

### ISSUE THREAD

**Issue by HDValentin** [encrypt-to/secure.contactform.php#4]
Wenn ich im Betreff meines Formulars "Test des verschlüsselten Formulars" eingebe, bekomme ich die Meldung, dass der Betreff nicht gültig sei. Link zum Testen: http://chillr.de/securemail/
Dies passiert ebenso, wenn ich Zahlen eingebe.

**Comment by mygithuber** [comment]
Hmmm, wenn ich das richtig gelesen haben, arbeitet send_form.php mit UTF-8:
$header = 'Content-Type: text/plain; charset=UTF-8' . "\n" .

Webserver und Seitenauslieferung laut FF ist ebenfalls auf UTF--8, aber im Quellcode nicht deklariert.
Vielleicht mal in \<head\> hinzufügen:
meta http-equiv="content-type" content="text/html; charset=utf-8" 

Gruß, gh

**Comment by HDValentin** [comment]
Ich habe es in der index.html ergänzt und es kommt die gleiche Fehlermeldung.

**Comment by mygithuber** [comment]
Hmmm, es scheint mit dieser Zeile in der send_form.php zusammenzuhängen

$string_exp = "/^[A-Za-z .'-]+$/";
  if(!preg_match($string_exp,$subject)) {
   	$error_message .= 'The Subject you entered does not appear to be valid.<br />';
  }

Die Variable $string_exp ist sehr restriktiv definiert. Ergänzt man 0-9 [A-Za-z0-9 .'-], gehen die Zahlen im Subject durch, an dt. Umlauten üöä verschluckt sich das Script trotzdem.

Kommentiert man die Zeilen komplett aus, wird das Script verschickt, es kommt keine Fehlermeldung (wie auch...), aber die Umlaute werden wg. der falschen Codierung auf Empfängerseite falsch dargestellt.

**Comment by jeromecc** [comment]
On 12/01/2015 09:47, mygithuber wrote:
>
> Hmmm, es scheint mit dieser Zeile in der send_form.php zusammenzuhängen
>
> $string_exp = "/^[A-Za-z .'-]+$/";
> if(!preg_match($string_exp,$subject)) {
> $error_message .= 'The Subject you entered does not appear to be valid.
> ';
> }
>
> Die Variable $string_exp ist sehr restriktiv definiert. Ergänzt man
> 0-9 [A-Za-z0-9 .'-], gehen die Zahlen im Subject durch, an dt.
> Umlauten üöä verschluckt sich das Script trotzdem.
>
> Kommentiert man die Zeilen komplett aus, wird das Script verschickt,
> es kommt keine Fehlermeldung (wie auch...), aber die Umlaute werden
> wg. der falschen Codierung auf Empfängerseite falsch dargestellt.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/encrypt-to/secure.contactform.php/issues/4#issuecomment-69541446>.
>
Hello!

It would be nice if you could speak english... :-)

Thank you!

Jérôme Pinguet
https://cryptoparty.fr

**Comment by mygithuber** [comment]
I'll try my best... ;)

If sending German Umlaute like üöäÜÖÄß or numbers in subject field, script rejects submission of encrypted mail with error message "The Subject you entered does not appear to be valid."

Subject's input check seems to be encoded in send_form.php:

$string_exp = "/^[A-Za-z .'-]+$/";
 if(!preg_match($string_exp,$subject)) { 
$error_message .= 'The Subject you entered does not appear to be valid. '; 
}

If commenting out these rows //, mail with numbers and German Umlaute in subject is sent, but recipient notices encoding errors with German Umlaute.

Variable $string_exp is defined very restrictiv. How to modify script for proper transmission of German Umlaute and numbers too?

Thanks and regards, mygithuber

**Comment by wiegelmann** [comment]
Feel free to make a pull request.

**Comment by mygithuber** [comment]
I did try:
https://github.com/HDValentin/secure.contactform.php/pull/1 
But ist seems to be not working :(

(Sorry, I am a newbie to github, not a programmer... )

**Comment by HDValentin** [comment]
Just made a pull request.

**Comment by wiegelmann** [comment]
Thanks

**Comment by HDValentin** [comment]
But ist solves this only for German text. What about all other languages which could be used in your script. Could ctype be  a solution? http://www.askingbox.de/artikel/php-strings-mit-ctype-funktionen-auf-zeichenklassen-ueberpruefen

**Comment by mygithuber** [comment]
Bei mir funktionieren Umlaute im Betreff immer noch nicht, die Ergänzung zu:
$string_exp = "/^[a-zA-Z0-9äöüÄÖÜß .'-]+$/";
hatte ich selber schon versucht!

Weiterhin arbeitet das Script mit einer älteren Version der openpgp.js: 0.72. 
Aktuell ist 0.9:
https://github.com/openpgpjs/openpgpjs/releases 

Danke + Gruß, g.

**Comment by HDValentin** [comment]
at http://chillr.de/securemail/ it is working correctly.
Probably because there ist  the  <meta http-equiv="content-type" content="text/html; charset=utf-8"/> in the html file made.

**Comment by HDValentin** [comment]
I've just made a push request for the chance.

**Comment by ciubotaru** [comment]
Yes, adding <meta charset=utf8> in html should solve this issue. Now you can remove the umlaut filter.

**Comment by mygithuber** [comment]
Ok, Umlaute üöäß and numbers in subject field are working under following conditions:

1. Modify send_form.php: 
$string_exp = "/^[a-zA-Z**0-9äöüÄÖÜß** .'-]+$/";

2. Declare UTF-8 in 'head' of contact.html:
'meta http-equiv="content-type" content="text/html; charset=utf-8" '

So, how to update openpgp.js to actual version 0.9?

Thanks and regards.

**Comment by wiegelmann** [comment]
@mygithuber The ruby branch is uptodate v0.9 - based on that you can create a pull request for the php version: https://github.com/encrypt-to/secure.contactform.ruby/commit/919e5685c99a1b57f4c068a9425b0d630214354b

**Comment by DanielRuf** [comment]
It makes no sense to limit the allowed characters to these. There are many more non-latin characters which are and can be used in subjects like other special characters because you use unicode as encoding.

It is much more safe to sanitize the subject and the text (body) of the email.

Some of the valid emails are identified as invalid: http://en.wikipedia.org/wiki/Email_address#Valid_email_addresses

Also the regex would fail with many of the new gTLDs: http://newgtlds.icann.org/en/program-status/delegated-strings

Never use regex for email validation, use DNS checks for example or there will be many problems with the new gTLDs
http://stackoverflow.com/questions/14123930/php-regex-for-gtlds
http://stackoverflow.com/questions/12026842/how-to-validate-an-email-address-in-php
http://stackoverflow.com/questions/3499192/validate-email-in-php
http://www.devshed.com/c/a/php/email-address-verification-with-php/2/
http://stackoverflow.com/questions/1076573/whats-wrong-with-this-regex-for-validating-emails
https://www.google.de/search?q=Don%27t+use+regular+expressions+to+validate+e-mail+addresses.&oq=Don%27t+use+regular+expressions+to+validate+e-mail+addresses.&aqs=chrome..69i57.337j0j4&sourceid=chrome&es_sm=0&ie=UTF-8
http://stackoverflow.com/questions/611775/regular-expression-for-valid-email-address
https://www.google.de/search?q=Rfc+6531&oq=Rfc+6531&aqs=chrome..69i57j0l4.178j0j4&sourceid=chrome&es_sm=0&ie=UTF-8

**Comment by wiegelmann** [comment]
@DanielRuf Thanks

**Comment by DanielRuf** [comment]
You are welcome.

Any idea what solution for the email validation should be used?
Should we create another issue for this?
